aplicacao:
  nome: '@project.name@'
  descricao: '@project.description@'
  versao: '@project.version@'


cliente-application.allows-origin: 0.0.0.0


spring.jpa.hibernate.naming.implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
spring.jpa.hibernate.naming.physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy

spring.datasource.url: jdbc:postgresql://localhost:5432/postgres
spring.datasource.username: postgres
spring.datasource.password: postgres


spring.jpa.database: POSTGRESQL
spring.datasource.platform: postgresql
spring.jpa.generate-ddl: true
spring.jpa.hibernate.ddl-auto: update

spring.jackson.deserialization.fail-on-unknown-properties: true
spring.jackson.date-format: yyyy-MM-dd

spring.flyway.schemas: public

spring:
  datasource:
    hikari:
      schema: public
  batch:
    initialize-schema: always
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  database:
    driverClassName: org.postgresql.Driver
  flyway:
    enabled: true
    baseline-on-migrate: true